"""
MkDocs hook: emit agent-readiness artifacts into the build output.

Two artifacts, both free-plan static assets (no Worker script, no paid
Cloudflare features):

1. Markdown twins — every built documentation page gets its markdown source
   copied next to its HTML output (site/<page>/index.md beside index.html,
   site/index.md for the homepage). Agents that prefer markdown fetch
   <page-url>index.md and skip the HTML entirely. This is the build-time
   half of the "Markdown for Agents" pattern; true Accept-header content
   negotiation needs a Worker script or Cloudflare's paid zone feature, so
   twins are the static-asset fallback (same pattern as Vercel's .md mirrors
   and Read the Docs' markdown-for-agents).

2. /.well-known/agent-skills/index.json — the Agent Skills Discovery index
   (RFC v0.2.0, github.com/cloudflare/agent-skills-discovery-rfc) advertising
   the public agentpatterns-ai/skills shelf. Copied verbatim from the "index"
   key of hooks/agent-skills-manifest.json, which is generated by
   scripts/generate-agent-skills-index.py and committed (the Cloudflare build
   clone cannot reach the skills repo — same committed-manifest pattern as
   lastmod-manifest.json).

3. /.well-known/mcp/server-card.json — MCP Server Card (SEP-1649 draft)
   advertising the site's public Cloudflare AI Search MCP endpoint (#9917).
   Copied verbatim from the committed hooks/mcp-server-card.json; the file's
   absence simply skips publication (no endpoint, no card).

4. /.well-known/api-catalog — RFC 9727 linkset cataloguing the site's
   agent-facing services (the AI Search public endpoint and MCP endpoint).
   Copied verbatim from the committed hooks/api-catalog.json; extensionless
   dest path per the RFC, content type set in docs/_headers.

Twins are copied verbatim, frontmatter included — the frontmatter carries the
description/tags/last_reviewed signals an agent wants anyway.
"""

import json
import logging
import shutil
from pathlib import Path

# The "mkdocs." prefix routes records through MkDocs' warning counter, so a
# missing/corrupt manifest fails `mkdocs build --strict` (CI) instead of
# silently shipping a site without the discovery index.
log = logging.getLogger("mkdocs.hooks.agent_readiness")

# ---------------------------------------------------------------------------
# Module-level state populated in on_config / on_files
# ---------------------------------------------------------------------------
_site_dir: Path | None = None

# (abs_src_path, dest_rel_path) pairs collected in on_files, written in
# on_post_build once the site tree exists.
_twins: list[tuple[Path, Path]] = []


def _manifest_index() -> dict | None:
    """Load the published index payload from the committed manifest."""
    manifest_path = Path(__file__).resolve().parent / "agent-skills-manifest.json"
    try:
        with manifest_path.open(encoding="utf-8") as fh:
            data = json.load(fh)
    except (FileNotFoundError, json.JSONDecodeError) as exc:
        log.warning(
            "agent_readiness: cannot load %s (%s) — "
            "/.well-known/agent-skills/index.json will NOT be published; "
            "run scripts/generate-agent-skills-index.py", manifest_path, exc,
        )
        return None
    try:
        index = data["index"]
        index["skills"]  # EAFP shape probe: malformed manifest → KeyError/TypeError
    except (KeyError, TypeError):
        log.warning(
            "agent_readiness: %s has no index.skills object — "
            "/.well-known/agent-skills/index.json will NOT be published", manifest_path,
        )
        return None
    return index


def _optional_json(filename: str, published: str) -> dict | None:
    """Committed-if-present JSON artifact (MCP server card, API catalog).

    Absence is not an error — these files exist only while the site exposes
    the corresponding service (#9917). A committed-but-corrupt file is loud:
    mkdocs-counted warning, fails --strict in CI.
    """
    path = Path(__file__).resolve().parent / filename
    if not path.exists():
        return None
    try:
        with path.open(encoding="utf-8") as fh:
            return json.load(fh)
    except json.JSONDecodeError as exc:
        log.warning(
            "agent_readiness: %s is not valid JSON (%s) — "
            "%s will NOT be published", path, exc, published,
        )
        return None


def on_config(config):
    global _site_dir, _twins
    _twins = []
    _site_dir = Path(config.get("site_dir") or "site")
    return config


def on_files(files, *, config, **kwargs):
    for file in files:
        if not file.src_path.endswith(".md"):
            continue
        if not file.is_documentation_page():
            continue
        dest = Path(file.dest_path)  # e.g. geo/what-is-geo/index.html
        if dest.suffix != ".html":
            continue
        _twins.append((Path(file.abs_src_path), dest.with_suffix(".md")))
    return files


def on_post_build(config):
    site_dir = _site_dir or Path("site")

    for abs_src, dest_rel in _twins:
        out_path = site_dir / dest_rel
        out_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(abs_src, out_path)

    index = _manifest_index()
    if index is not None:
        out_path = site_dir / ".well-known" / "agent-skills" / "index.json"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8") as fh:
            json.dump(index, fh, indent=2, ensure_ascii=False)
            fh.write("\n")

    card = _optional_json("mcp-server-card.json", "/.well-known/mcp/server-card.json")
    if card is not None:
        out_path = site_dir / ".well-known" / "mcp" / "server-card.json"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8") as fh:
            json.dump(card, fh, indent=2, ensure_ascii=False)
            fh.write("\n")

    # RFC 9727: the catalog's well-known path is extensionless; the
    # application/linkset+json content type comes from docs/_headers.
    catalog = _optional_json("api-catalog.json", "/.well-known/api-catalog")
    if catalog is not None:
        out_path = site_dir / ".well-known" / "api-catalog"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8") as fh:
            json.dump(catalog, fh, indent=2, ensure_ascii=False)
            fh.write("\n")

    # /auth.md (WorkOS auth.md convention, honest no-auth variant — #9917
    # follow-up): plain markdown, copied verbatim when committed. It cannot
    # live under docs/ because MkDocs would render it to /auth/ HTML; the
    # convention requires raw markdown at exactly /auth.md.
    auth_src = Path(__file__).resolve().parent / "auth.md"
    auth_published = auth_src.exists()
    if auth_published:
        shutil.copyfile(auth_src, site_dir / "auth.md")

    print(f"agent_readiness.py: wrote {len(_twins)} markdown twin(s)"
          + ("" if index is None else f" + agent-skills index ({len(index.get('skills', []))} skills)")
          + ("" if card is None else " + mcp server card")
          + ("" if catalog is None else " + api catalog")
          + ("" if not auth_published else " + auth.md"))
